### PR TITLE
Features to a new a version (1.0 (?))

### PR DESCRIPTION
**Pull request by bor-attila**
This PR is a set of changes what I appled to the plugin. Please feel free to reject if not needed : )

Testing needed!

- removed ViteCommand. [You can configure the vitejs to clean up build dir with on every build](https://vitejs.dev/config/build-options.html#build-emptyoutdir)
- removed deprecated ViteHelper
- removed `devPort` use the `developmentUrl` instead (solves #4)
- removed `manifestDir`. was replaced with `build.manifest`
- removed `jsSrcDirectory` and `mainJS` configuration. Was replaced by parameters when calling the helper method
- changed minimum PHP version from 7.x to 8.x
- the helper methods was renamed (head and body) to (script and css) now "appends" the generated output to the `View::fetch('script')` and `View::fetch('css')`
- update vitejs example in the `etc` dir (maybe solves(?)/gives an example(?) for #3) (?)
- added some test cases
- updated README
- added bugs (probably :))

Since there is no `mainJS` configuration the [rollupOptions.input](https://vitejs.dev/config/build-options.html#build-rollupoptions) accepts an array<string> instead of string.

### CODE REVIEW

**Comment by passchn** [comment]
Thank you! This looks very promising on first sight. I fear that I won't find the time to look into it before/during Christmas. We should definitely work towards a v1.0 :)

**Comment by t0byman** [comment]
Nice improvements! Some feedback:

- A lot of front-end developers are leaving SCSS behind and are working with PostCSS which is just a .css file so please remove `.scss` in `:host/:file.scss` so I can do this `<?= $this->ViteScripts->css(['styles/main.css']) ?>`
- A lot of front-end developers are leaving vanilla JavaScript behind and are working with TypeScript which is a .ts file so please remove `.js` in `:host/:file.js` so I can do this `<?= $this->ViteScripts->script(['scripts/main.ts']) ?>`
- When testing loading files from manifest, it can find my manifest but it doesn't try to load the files at all, not even a 404 my overwrites in app.php is:
```
    'ViteHelper' => [
		'build' => [
			'outDir' => '/var/www/html/webroot/dist',
			'manifest' => '/var/www/html/webroot/dist/manifest.json',
		],
		'developmentUrl' => 'http://localhost:5173', // you get that port when using dns.setDefaultResultOrder('verbatim'); in vite.config.js
		'forceProductionMode' => true,
    ],
```
and my vite.config.js build is:
```
build: {
      manifest: true,
      rollupOptions: {
        input: {
          // Styles
          styles: './resources/styles/main.css',
          critical: './resources/styles/critical.css',

          // Scripts
          main: './resources/scripts/main.ts',
        },
        output: {
          entryFileNames: 'assets/[name]-[hash].js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash].[ext]',
        },
      },
      outDir: '../webroot/dist',
      emptyOutDir: true,
    },
```
and my manifest.json is:
```
{
  "styles/main.css": {
    "file": "assets/main-186c74ee.css",
    "src": "styles/main.css",
    "isEntry": true
  },
  "styles/critical.css": {
    "file": "assets/critical-d23d9f7b.css",
    "src": "styles/critical.css",
    "isEntry": true
  },
  "scripts/components/TanButton.ce.vue": {
    "file": "assets/TanButton.ce-90dcaab6.js",
    "src": "scripts/components/TanButton.ce.vue",
    "isDynamicEntry": true,
    "imports": [
      "scripts/main.ts"
    ]
  },
  "scripts/main.ts": {
    "file": "assets/main-80ba8744.js",
    "src": "scripts/main.ts",
    "isEntry": true,
    "dynamicImports": [
      "scripts/components/TanButton.ce.vue"
    ]
  }
}
```

**Comment by t0byman** [comment]
> Thank you! This looks very promising on first sight. I fear that I won't find the time to look into it before/during Christmas. We should definitely work towards a v1.0 :)

No pressure or anything but do you maybe have an ETA? :)

**Comment by passchn** [comment]
@t0byman this weekend. Was a bit busy the last weeks, I'm sorry.

**Comment by t0byman** [comment]
> @t0byman this weekend. Was a bit busy the last weeks, I'm sorry.

Don’t be sorry mate, you’re a legend for making this!

**Comment by passchn** [comment]
lol :D Thanks! I am actually looking into it right now.

**Comment by passchn** [comment]
@bor-attila I merged your PR into a new branch which will used to work towards a v1.0:
https://github.com/brandcom/cakephp-vite/tree/future/v1 

I tried to make it run locally and also added a migration guide with the necessary changes: 
https://github.com/brandcom/cakephp-vite/blob/future/v1/docs/Migrating%20to%20version%201.x 

I also did some code changes because I ran in the problem @t0byman mentioned, e.g. I am using scss and ts. So this should be set in the config. 

I am also not really happy about the fact that the entry points/$files should be passed to the helper. Can't this be a config thing or can't we let the Manifest figure it out? 

Have to admit that I only tried to make it run tonight. I'll take a deeper look on the weekend :)

**Comment by passchn** [comment]
Update: Prettier migration guide: 
https://github.com/brandcom/cakephp-vite/blob/future/v1/docs/Migrating%20to%20version%201.x.md

**Comment by passchn** [comment]
I think the config should get some better namings. People coming from webpack or gulp usually don't get that vite is serving on its own domain/port during development and it is *not* also serving your php. 

So maybe we could nest these options to separate the php-server from the js-server... 

```php
'developmentUrl' => ConfigDefaults::DEVELOPMENT_URL,
'developmentHostNeedles' => ConfigDefaults::DEV_HOST_NEEDLES,
```

**Pull request merged**
